import './css/style.css';
import './js/app';
import './js/Character';
import './js/Bowman';
import './js/Magician';
import './js/Swordsman';
import './js/Daemon';
import './js/Undead';
import './js/Zombie';
